// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdAkNvZ3JkM-GmWBKf9eZ1p0LwZmj7rOE',
    appId: '1:933667639572:web:afcd53aafe2e3f1405b201',
    messagingSenderId: '933667639572',
    projectId: 'project1-b718c',
    authDomain: 'project1-b718c.firebaseapp.com',
    storageBucket: 'project1-b718c.firebasestorage.app',
    measurementId: 'G-E9YYKMPD3J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAVfNUEnCSBL2SHwqtWZ8Z2PTqlL4GKsM',
    appId: '1:933667639572:android:d3e0374afe38ee3105b201',
    messagingSenderId: '933667639572',
    projectId: 'project1-b718c',
    storageBucket: 'project1-b718c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-PNzL0M3LdfImgWY_PJQY4svU2kK47uo',
    appId: '1:933667639572:ios:640692f0500d73e205b201',
    messagingSenderId: '933667639572',
    projectId: 'project1-b718c',
    storageBucket: 'project1-b718c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-PNzL0M3LdfImgWY_PJQY4svU2kK47uo',
    appId: '1:933667639572:ios:640692f0500d73e205b201',
    messagingSenderId: '933667639572',
    projectId: 'project1-b718c',
    storageBucket: 'project1-b718c.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdAkNvZ3JkM-GmWBKf9eZ1p0LwZmj7rOE',
    appId: '1:933667639572:web:01c457712ebf45be05b201',
    messagingSenderId: '933667639572',
    projectId: 'project1-b718c',
    authDomain: 'project1-b718c.firebaseapp.com',
    storageBucket: 'project1-b718c.firebasestorage.app',
    measurementId: 'G-1DKFR1YLEY',
  );
}
